Force secure connection to speedtest.net
It seems that the speedtest servers return random 403 errors when the speedtest client uses http. Forcing the client to use https fixes this and I no longer see the exception being thrown in my logs after running for some time.

```
Exception happened during processing of request from ('<redacted>', 37976)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/prometheus_speedtest/prometheus_speedtest.py", line 125, in __init__
    super().__init__(directory=static_directory, *args, **kwargs)
  File "/usr/local/lib/python3.7/http/server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/prometheus_speedtest/prometheus_speedtest.py", line 137, in do_GET
    prometheus_client.MetricsHandler.do_GET(self)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 169, in do_GET
    status, header, output = _bake_output(registry, accept_header, params)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 40, in _bake_output
    output = encoder(registry)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 82, in collect
    for metric in collector.collect():
  File "/prometheus_speedtest/prometheus_speedtest.py", line 92, in collect
    results = self._tester.test()
  File "/prometheus_speedtest/prometheus_speedtest.py", line 60, in test
    timeout=self._timeout)
  File "/usr/local/lib/python3.7/site-packages/speedtest.py", line 1095, in __init__
    self.get_config()
  File "/usr/local/lib/python3.7/site-packages/speedtest.py", line 1127, in get_config
    raise ConfigRetrievalError(e)
speedtest.ConfigRetrievalError: HTTP Error 403: Forbidden
```